// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAreMJnSbx90_rnHdOmjX78_L9B-Ru0h5g',
    appId: '1:1083086468448:web:5be126f44362bafb47da05',
    messagingSenderId: '1083086468448',
    projectId: 'loginflutter-8d68f',
    authDomain: 'loginflutter-8d68f.firebaseapp.com',
    storageBucket: 'loginflutter-8d68f.firebasestorage.app',
    measurementId: 'G-NBB2XKT4CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG1mYTp2lqSGg1rLy1MYP72L0JidVSC5E',
    appId: '1:1083086468448:android:8a00921e77a32c4047da05',
    messagingSenderId: '1083086468448',
    projectId: 'loginflutter-8d68f',
    storageBucket: 'loginflutter-8d68f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMHc-uptMdASVQBQgfj-LX3qQC95GJkJ8',
    appId: '1:1083086468448:ios:ed37e6666d1c294147da05',
    messagingSenderId: '1083086468448',
    projectId: 'loginflutter-8d68f',
    storageBucket: 'loginflutter-8d68f.firebasestorage.app',
    iosBundleId: 'com.autenticacionflutter.loginfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMHc-uptMdASVQBQgfj-LX3qQC95GJkJ8',
    appId: '1:1083086468448:ios:ed37e6666d1c294147da05',
    messagingSenderId: '1083086468448',
    projectId: 'loginflutter-8d68f',
    storageBucket: 'loginflutter-8d68f.firebasestorage.app',
    iosBundleId: 'com.autenticacionflutter.loginfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAreMJnSbx90_rnHdOmjX78_L9B-Ru0h5g',
    appId: '1:1083086468448:web:c4dd5f311073874647da05',
    messagingSenderId: '1083086468448',
    projectId: 'loginflutter-8d68f',
    authDomain: 'loginflutter-8d68f.firebaseapp.com',
    storageBucket: 'loginflutter-8d68f.firebasestorage.app',
    measurementId: 'G-SRNYNNEZ9S',
  );

}